export const SCHEDULABLE_STATUSES = [
  "ACCEPTED",
  "PAYMENT_PENDING",
  "PAYMENT_SUBMITTED",
  "PAYMENT_VERIFICATION",
  "PAYMENT_REJECTED",
  "CONFIRMED",
  "IN_PRODUCTION",
  "READY_TO_SHIP",
] as const;

export const INACTIVE_STATUSES = [
  "CANCELLED",
  "REFUNDED",
  "REJECTED",
  "SHIPPED",
  "DELIVERED",
  "PAYMENT_REJECTED",
] as const;
